# Generated by Django 6.1 on 2026-08-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['started_at']},
        ),
        migrations.AddField(
            model_name='attempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
